version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[NPM]"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[GEM]"
    update-types:
    - "minor"
    # ignore:
    #   - dependency-name: "*"
    #     update-types: ["version-update:semver-major"]
